import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
const DATA=process.env.DATA_DIR||path.resolve('data'), FILE=path.join(DATA,'state-v4.2-live.json'), FEE=.0225;
export function freshV42(now=Date.now()){return{version:4.2,build:'v4.2-intelligence-ab',startedAt:now,endsAt:now+5*86400000,initialCash:10,cash:10,realizedPnl:0,equityPeak:10,lastScan:null,candidates:{},positions:[],orders:[],trades:[],decisions:[]}}
export function loadV42(){fs.mkdirSync(DATA,{recursive:true});if(!fs.existsSync(FILE)){let s=freshV42();saveV42(s);return s}try{return{...freshV42(),...JSON.parse(fs.readFileSync(FILE,'utf8')),version:4.2,build:'v4.2-intelligence-ab'}}catch{let s=freshV42();saveV42(s);return s}}
export function saveV42(s){fs.writeFileSync(FILE,JSON.stringify(s,null,2))}
const open=s=>s.positions.filter(p=>p.quantity>0&&!p.closedAt), pend=s=>s.orders.filter(o=>o.status==='pending'), mark=(s,k)=>s.candidates[k]?.last?.price||0;
export const equity42=s=>s.cash+open(s).reduce((z,p)=>z+p.quantity*mark(s,p.key),0);
const dec=(s,r)=>{s.decisions.unshift({id:crypto.randomUUID(),at:Date.now(),...r});if(s.decisions.length>1000)s.decisions.length=1000};
function enrich(s,t,now){let c=s.candidates[t.key]||={samples:[]};c.samples.push({at:now,price:t.price,liq:t.liquidity,vol:t.volume5m,buys:t.buys5m});if(c.samples.length>8)c.samples.shift();c.last=t;c.lastSeenAt=now;let f=c.samples[0],l=c.samples.at(-1),pct=(a,b)=>a>0?(b-a)/a*100:0;let pm=pct(f.price,l.price),lg=pct(f.liq,l.liq),vg=pct(f.vol,l.vol),ba=l.buys-f.buys;let score=(t.liquidity>=5000?15:0)+(t.volume5m>=1000?15:0)+(t.buys5m>=12?10:0)+(t.buySellRatio>=1.35?15:0)+(t.ageMinutes!=null&&t.ageMinutes<=120?10:0)+(pm>0&&pm<=35?15:0)+(lg>=0?10:0)+(vg>=0?5:0)+(ba>=0?5:0);return{...t,intelligenceScore:score,priceMomentum:pm,liquidityGrowth:lg,volumeGrowth:vg,buyAcceleration:ba,samples:c.samples.length}}
function blocks(s,t,now){let b=[];if(!(t.price>0))b.push('price');if(t.liquidity<5000)b.push('liquidity');if(t.volume5m<1000)b.push('volume_5m');if(t.buys5m<12)b.push('buys_5m');if(t.buySellRatio<1.35)b.push('buy_sell_ratio');if(t.ageMinutes==null||t.ageMinutes>120)b.push('pool_age');if(t.samples<3)b.push('observation_depth');if(t.priceMomentum<0)b.push('negative_momentum');if(t.priceMomentum>35)b.push('chasing_spike');if(t.liquidityGrowth<-8)b.push('liquidity_drain');if(t.volumeGrowth<-25)b.push('volume_decay');let x=s.trades.filter(x=>x.key===t.key).sort((a,b)=>b.at-a.at)[0];if(x&&now-x.at<(x.reason==='stop_loss'?30:15)*60000)b.push('reentry_cooldown');return b}
export function observeV42(s,raw,now=Date.now()){let t=enrich(s,raw,now),base={key:t.key,symbol:t.symbol,score:t.intelligenceScore};if(now>=s.endsAt)return dec(s,{...base,status:'rejected',reason:'session_ended'});if(open(s).some(p=>p.key===t.key))return dec(s,{...base,status:'rejected',reason:'position_already_open'});if(pend(s).some(o=>o.key===t.key))return dec(s,{...base,status:'rejected',reason:'order_already_pending'});let bad=blocks(s,t,now);if(bad.length)return dec(s,{...base,status:'rejected',reason:bad.join(','),metrics:t});if(t.intelligenceScore<80)return dec(s,{...base,status:'rejected',reason:'intelligence_score'});if(open(s).length+pend(s).length>=4)return dec(s,{...base,status:'rejected',reason:'max_positions'});let n=Math.min(equity42(s)*.06,s.cash/(1+FEE));if(n<.1)return dec(s,{...base,status:'rejected',reason:'insufficient_free_cash'});let o={id:crypto.randomUUID(),key:t.key,symbol:t.symbol,status:'pending',side:'buy',createdAt:now,readyAt:now+3500,deadline:now+120000,notional:n,score:t.intelligenceScore};s.orders.unshift(o);dec(s,{...base,status:'accepted',reason:'v42_paper_entry_queued',orderId:o.id})}
function sell(s,p,q,price,reason,now){q=Math.min(q,p.quantity);let frac=q/p.quantity,cost=p.remainingCost*frac,proceeds=q*price*(1-FEE),pnl=proceeds-cost;p.quantity-=q;p.remainingCost-=cost;s.cash+=proceeds;s.realizedPnl+=pnl;s.trades.push({id:crypto.randomUUID(),positionId:p.id,key:p.key,symbol:p.symbol,quantity:q,cost,proceeds,pnl,reason,at:now});if(p.quantity<=1e-12){p.quantity=0;p.remainingCost=0;p.closedAt=now}}
export function processV42(s,now=Date.now()){for(let o of pend(s).filter(x=>x.readyAt<=now)){let t=s.candidates[o.key]?.last;if(!t||now>o.deadline){o.status='cancelled';o.reason='stale';continue}let total=o.notional*(1+FEE);if(s.cash<total){o.status='cancelled';o.reason='cash';continue}let q=o.notional/t.price;s.cash-=total;let p={id:crypto.randomUUID(),key:o.key,symbol:o.symbol,quantity:q,initialQuantity:q,entryPrice:t.price,entryCost:total,remainingCost:total,openedAt:now,peakPrice:t.price,principalTaken:false,scaled:false};s.positions.push(p);o.status='filled';o.filledAt=now;o.positionId=p.id;dec(s,{key:o.key,symbol:o.symbol,status:'filled',reason:'v42_paper_entry_filled'})}for(let p of open(s)){let t=s.candidates[p.key]?.last;if(!t?.price)continue;let price=t.price;p.peakPrice=Math.max(p.peakPrice||p.entryPrice,price);let m=price/p.entryPrice;if(price<=p.entryPrice*.72){sell(s,p,p.quantity,price,'stop_loss',now);continue}if(!p.principalTaken&&m>=2){sell(s,p,Math.min(p.quantity,p.entryCost/(1-FEE)/price),price,'principal_recovery',now);p.principalTaken=true;continue}if(!p.scaled&&m>=3){sell(s,p,p.quantity*.35,price,'runner_scale',now);p.scaled=true;continue}if(p.principalTaken&&price<=p.peakPrice*.72)sell(s,p,p.quantity,price,'protected_runner_exit',now)}let e=equity42(s);s.equityPeak=Math.max(s.equityPeak,e);s.lastScan=now}
export function summary42(s){let e=equity42(s),op=open(s);return{build:s.build,version:s.version,startedAt:s.startedAt,endsAt:s.endsAt,initialCash:s.initialCash,cash:s.cash,equity:e,realizedPnl:s.realizedPnl,unrealizedPnl:e-s.cash-op.reduce((z,p)=>z+p.remainingCost,0),returnPct:(e/s.initialCash-1)*100,drawdownPct:(s.equityPeak-e)/s.equityPeak*100,openPositions:op.length,pendingBuys:pend(s).length,positions:s.positions,orders:s.orders,trades:s.trades}}
